source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'AFNetworking', '~> 2.5'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'PureLayout'
pod 'MGSwipeTableCell'
pod 'CTAssetsPickerController',  '~> 3.2.0'
pod 'CLImageEditor/AllTools'